twitter-to-kafka-service:
  twitter-keywords:
    - "Java"
    - "Microservices"
    - "Spring"
    - "kafka"
    - "ElasticSearch"
  welcome-message: "Test Hello :)"
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
